site_name: KriveBot
site_description: 'Dokumentacja bota KriveBot'
site_author: 'Korrumz2PL'
docs_dir: docs/
repo_name: 'Korrumz2PL/docs-public'
repo_url: 'https://github.com/Korrumz2PL/docs-public'
nav:
    - Home: index.md
theme:
  name: 'material'
