site_name: Dokumentacja
site_description: 'Dokumentacja bota KriveBot'
site_author: 'Korrumz2PL'
docs_dir: docs/
repo_name: 'Korrumz2PL/docs-public'
repo_url: 'https://github.com/Korrumz2PL/docs-public'
nav:
    - Strona główna: index.md
    - Konfiguracja: config.md
    - Rodziny: families.md
    - Moderacja: moderation.md
    - Anty-raid: antyraid.md
    - Profile: profiles.md
    - Permisje: perms.md
    - Logi: logs.md
    - Zabawa: fun.md
    - Strona: site.md
    - Lockdown: lockdown.md
    - Tickety: tickets.md 
    - Changelog: changelog.md
theme:
  language: pl
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Tryb ciemny
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Tryb jasny
  name: material
  features:
    - navigation
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - header.autohide
    - navigation.expand
    - navigation.indexes
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - admonition
  - attr_list
