site_name: Dokumentacja
site_description: 'Dokumentacja bota KriveBot'
site_author: 'Korrumz2PL'
docs_dir: docs/
repo_name: 'Korrumz2PL/docs-public'
repo_url: 'https://github.com/Korrumz2PL/krivebot'
nav:
    - Strona główna: home.md
    - Konfiguracja: config.md
    - Rodziny: families.md
theme:
  name: 'material'
